version: '3'
services:
  oh-btc:
    build: 
      context: .
      dockerfile: ./main/docker/Dockerfile
    image: oh-btc
    container_name: oh-btc
    ports:
    - "8080:8080"
    command: > 
      sh -c "npm run start"